apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "golang-server-boilerplate.configmapName" . }}
  labels:
    {{- include "golang-server-boilerplate.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.app.port | quote }}
  LOG_FORMAT: {{ .Values.app.logFormat | quote }}
  CHECK_INTERVAL: {{ .Values.app.checkInterval | quote }}
  STATE_PATH: {{ .Values.app.statePath | quote }}
  IP_URLS: {{ .Values.app.ipUrls | quote }}
