apiVersion: v1
kind: Secret
metadata:
  name: {{ include "golang-server-boilerplate.secretName" . }}
  labels:
    {{- include "golang-server-boilerplate.labels" . | nindent 4 }}
type: Opaque
data: {}
  # Add base64-encoded secrets as needed, e.g.:
  # API_KEY: <base64-encoded-value>
