apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: watcher-email
  namespace: default
spec:
  encryptedData:
    EMAIL_HOST_NAME: AgReplaceThisWithKubesealOutput
    EMAIL_PASSWORD: AgReplaceThisWithKubesealOutput
    EMAIL_PERSONAL_EMAIL: AgReplaceThisWithKubesealOutput
    EMAIL_PORT: AgReplaceThisWithKubesealOutput
    EMAIL_TLS: AgReplaceThisWithKubesealOutput
    EMAIL_USERNAME: AgReplaceThisWithKubesealOutput
  template:
    metadata:
      name: watcher-email
      namespace: default
    type: Opaque
