apiVersion: v2
name: watcher-in-the-water
description: Monitor your home network’s public IP address changes.
type: application
version: 0.0.0-alpha
appVersion: "0.0.0-alpha"
keywords:
  - go
  - http
  - server
  - boilerplate
home: https://github.com/nwthomas/watcher-in-the-water
sources:
  - https://github.com/nwthomas/watcher-in-the-water
maintainers:
  - name: Nathan Thomas
    email: contact@nathanthomas.dev
